@ECHO OFF
ECHO Compile all THREADS Subroutines for DOS
CALL COMPTHR THZ 
CALL COMPTHR THZALLC     
CALL COMPTHR THZCLOS 
CALL COMPTHR THZDFPT  
CALL COMPTHR THZDROP  
CALL COMPTHR THZPOP   
CALL COMPTHR THZPUSH  
CALL COMPTHR THZSEND  
CALL COMPTHR DFS
CALL COMPTHR THZCREP  
CALL COMPTHR THZRECV
CALL COMPTHR THXSCAN  
CALL COMPTHR THXGATRS 
CALL COMPTHR THXFCBS  
CALL COMPTHR THXDCBS  
CALL COMPTHR THXGEN   
CALL COMPTHR THREADS