@ECHO OFF
ECHO Compile all components for DOS
CALL COMPCMP THVIEW   
CALL COMPCMP THGENIPS 
CALL COMPCMP THENCBRK 
CALL COMPCMP THREMBRK 
CALL COMPCMP THREVERS 
CALL COMPCMP THDROP   
CALL COMPCMP THMERGE  
CALL COMPCMP THFILERD 
CALL COMPCMP THCOUNT  
CALL COMPCMP THREPL   
CALL COMPCMP THASSIGN 
CALL COMPCMP THCOLL8  
CALL COMPCMP THCOUNTM 
CALL COMPCMP THFILERB 
CALL COMPCMP THFILERT 
CALL COMPCMP THSPLIT  
CALL COMPCMP THSPLITT 
CALL COMPCMP THFILEWT