@ECHO OFF
ECHO Compile all components as DLLs for THREADS/Windows
CALL COMPDLLW THVIEW   
CALL COMPDLLW THGENIPS 
CALL COMPDLLW THENCBRK 
CALL COMPDLLW THREMBRK 
CALL COMPDLLW THREVERS 
CALL COMPDLLW THDROP   
CALL COMPDLLW THMERGE  
CALL COMPDLLW THFILERD 
CALL COMPDLLW THCOUNT  
CALL COMPDLLW THREPL   
CALL COMPDLLW THASSIGN 
CALL COMPDLLW THCOLL8  
CALL COMPDLLW THCOUNTM 
CALL COMPDLLW THFILERB 
CALL COMPDLLW THFILERT 
CALL COMPDLLW THSPLIT  
CALL COMPDLLW THSPLITT 
CALL COMPDLLW THFILEWT
CALL COMPDLLW THFILEBN 