@ECHO OFF
ECHO Compile all THREADS subroutines for Windows
CALL COMPTHRW THZ   
CALL COMPTHRW THZALLC     
CALL COMPTHRW THZCLOS  
CALL COMPTHRW THZDFPT  
CALL COMPTHRW THZDROP  
CALL COMPTHRW THZPOP   
CALL COMPTHRW THZPUSH  
CALL COMPTHRW THZSEND  
CALL COMPTHRW DFS
CALL COMPTHRW THZCREP  
CALL COMPTHRW THZRECV
CALL COMPTHRW THXSCAN  
CALL COMPTHRW THXGATRS 
CALL COMPTHRW THXFCBS  
CALL COMPTHRW THXDCBS  
CALL COMPTHRW THXGEN   
CALL COMPTHRW THREADS  
CALL COMPTHRW LIBMAIN
CALL COMPTHRW THXBOOT